name: Push to jangya.github.io

on: workflow_dispatch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Push to jangya.github.io
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "dist"
          destination-github-username: "jangya"
          destination-repository-name: "jangya.github.io"
          user-email: jangya069@gmail.com
          target-branch: main
